# Generated by Django 6.0.4 on 2026-04-24 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Endereco',
            new_name='EnderecoUsuario',
        ),
    ]
