# Generated by Django 6.0.4 on 2026-04-28 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_endereco_enderecousuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('foto_principal', models.CharField(max_length=255)),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('oculto', 'Oculto'), ('vendido', 'Vendido'), ('disponivel', 'Disponivel')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='EnderecoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=100)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(max_length=9)),
                ('localidade', models.CharField(max_length=100)),
                ('sigla_federacao', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(max_length=255, null=True, upload_to='usuario/profile'),
        ),
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('imovel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.imovel')),
                ('area_util', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_dormitorios', models.IntegerField()),
                ('numero_suites', models.IntegerField()),
            ],
            bases=('core.imovel',),
        ),
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('imovel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.imovel')),
                ('area_terreno', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_construcao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_dormitorios', models.IntegerField()),
                ('numero_suites', models.IntegerField()),
            ],
            bases=('core.imovel',),
        ),
        migrations.CreateModel(
            name='Chacara',
            fields=[
                ('imovel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.imovel')),
                ('area_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_construida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_casas', models.IntegerField()),
            ],
            bases=('core.imovel',),
        ),
        migrations.CreateModel(
            name='GalpaoComercial',
            fields=[
                ('imovel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.imovel')),
                ('area_util', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            bases=('core.imovel',),
        ),
        migrations.CreateModel(
            name='SalaComercial',
            fields=[
                ('imovel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.imovel')),
                ('area_util', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            bases=('core.imovel',),
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('imovel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.imovel')),
                ('area_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('benfeitorias', models.TextField()),
            ],
            bases=('core.imovel',),
        ),
        migrations.CreateModel(
            name='Terreno',
            fields=[
                ('imovel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.imovel')),
                ('metragem', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            bases=('core.imovel',),
        ),
        migrations.AddField(
            model_name='imovel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imovel',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.enderecoimovel'),
        ),
        migrations.CreateModel(
            name='FotosImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caminho', models.ImageField(max_length=255, upload_to='imoveis/galeria')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imovel')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_pedido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('preco_final', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_publicacao', models.DateField(auto_now_add=True)),
                ('data_fechamento', models.DateField(null=True)),
                ('observacoes', models.TextField()),
                ('status', models.CharField(choices=[('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('executando', 'Executando')], max_length=15)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprador', to=settings.AUTH_USER_MODEL)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.imovel')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendedor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalhesApartamento',
            fields=[
                ('apartamento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.apartamento')),
                ('bloco', models.CharField(max_length=15)),
                ('andar', models.CharField(max_length=15)),
            ],
            bases=('core.apartamento',),
        ),
    ]
