# Generated by Django 6.0.4 on 2026-09-10 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_imovel_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('corretor', 'Corretor / Vendedor'), ('proprietario', 'Proprietário'), ('comprador', 'Comprador')], default='comprador', max_length=20),
        ),
    ]
