# Generated by Django 6.0.4 on 2026-09-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_usuario_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='valor_original',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
